name: build
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Omit commits with `[skip ci]` in latest commit (like Bitbucket Pipelines)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Check out
        uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
