on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [arm-unknown-linux-musleabi]
    steps:
      - uses: actions/checkout@master
      - run: rustup target add arm-unknown-linux-musleabi
      - name: Compile and release
        uses: Douile/rust-build.action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "assets media"
