on:
  release:
    types: [created]

jobs:
  release:
    name: Create release for Pi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [armv7-unknown-linux-gnueabihf]
    steps:
      - name: Check out
        uses: actions/checkout@master
      - name: Install target compiler
        run: sudo apt-get install -y --no-install-recommends gcc-multilib-arm-linux-gnueabihf
      - name: Install target rust toolchain
        run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Compile and release
        uses: Douile/rust-build.action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "assets media"
