on:
  release:
    types: [created]

jobs:
  release:
    name: Create release for Pi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [armv7-unknown-linux-gnueabihf]
    steps:
      - uses: actions/checkout@master
      - run: apt-get install -y --no-install-recommends gcc-4.7-multilib-arm-linux-gnueabihf
      - run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Compile and release
        uses: Douile/rust-build.action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "assets media"
